# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_watermark.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_watermark(object):
    def setupUi(self, watermark):
        watermark.setObjectName("watermark")
        watermark.resize(1160, 810)
        self.commandbar = CommandBar(watermark)
        self.commandbar.setGeometry(QtCore.QRect(0, 40, 541, 34))
        self.commandbar.setObjectName("commandbar")
        self.work_button = TransparentPushButton(watermark)
        self.work_button.setGeometry(QtCore.QRect(390, 630, 176, 30))
        self.work_button.setObjectName("work_button")
        self.video = QVideoWidget(watermark)
        self.video.setGeometry(QtCore.QRect(20, 90, 960, 540))
        self.video.setObjectName("video")

        self.retranslateUi(watermark)
        QtCore.QMetaObject.connectSlotsByName(watermark)

    def retranslateUi(self, watermark):
        _translate = QtCore.QCoreApplication.translate
        watermark.setWindowTitle(_translate("watermark", "Form"))
        self.work_button.setText(_translate("watermark", "添加水印"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
from qfluentwidgets import CommandBar, TransparentPushButton
