# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_mosaic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mosaic(object):
    def setupUi(self, mosaic):
        mosaic.setObjectName("mosaic")
        mosaic.resize(1160, 810)
        self.video_slider = Slider(mosaic)
        self.video_slider.setGeometry(QtCore.QRect(0, 640, 991, 21))
        self.video_slider.setMaximum(1000)
        self.video_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.video = QtWidgets.QGraphicsView(mosaic)
        self.video.setGeometry(QtCore.QRect(20, 90, 960, 540))
        self.video.setObjectName("video")
        self.cut_button = ToolButton(mosaic)
        self.cut_button.setGeometry(QtCore.QRect(470, 710, 38, 32))
        self.cut_button.setObjectName("cut_button")
        self.commandbar = CommandBar(mosaic)
        self.commandbar.setGeometry(QtCore.QRect(0, 40, 541, 34))
        self.commandbar.setObjectName("commandbar")
        self.next_frame = ToolButton(mosaic)
        self.next_frame.setGeometry(QtCore.QRect(530, 670, 38, 32))
        self.next_frame.setObjectName("next_frame")
        self.play_button = ToolButton(mosaic)
        self.play_button.setGeometry(QtCore.QRect(470, 670, 38, 32))
        self.play_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.play_button.setText("")
        self.play_button.setObjectName("play_button")
        self.last_frame = ToolButton(mosaic)
        self.last_frame.setGeometry(QtCore.QRect(420, 670, 38, 32))
        self.last_frame.setObjectName("last_frame")
        self.choose_face = ComboBox(mosaic)
        self.choose_face.setGeometry(QtCore.QRect(990, 220, 91, 32))
        self.choose_face.setObjectName("choose_face")
        self.faces = PlainTextEdit(mosaic)
        self.faces.setGeometry(QtCore.QRect(630, 660, 256, 141))
        self.faces.setObjectName("faces")

        self.retranslateUi(mosaic)
        QtCore.QMetaObject.connectSlotsByName(mosaic)

    def retranslateUi(self, mosaic):
        _translate = QtCore.QCoreApplication.translate
        mosaic.setWindowTitle(_translate("mosaic", "Form"))
from qfluentwidgets import ComboBox, CommandBar, PlainTextEdit, Slider, ToolButton
