# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_remove_watermark.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_remove(object):
    def setupUi(self, remove):
        remove.setObjectName("remove")
        remove.resize(1160, 810)
        self.commandbar = CommandBar(remove)
        self.commandbar.setGeometry(QtCore.QRect(0, 0, 541, 34))
        self.commandbar.setObjectName("commandbar")
        self.work_button = TransparentPushButton(remove)
        self.work_button.setGeometry(QtCore.QRect(340, 660, 176, 30))
        self.work_button.setObjectName("work_button")
        self.video = QtWidgets.QGraphicsView(remove)
        self.video.setGeometry(QtCore.QRect(10, 40, 960, 540))
        self.video.setObjectName("video")
        self.video_slider = Slider(remove)
        self.video_slider.setGeometry(QtCore.QRect(10, 580, 961, 21))
        self.video_slider.setMaximum(1000)
        self.video_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.play_button = ToolButton(remove)
        self.play_button.setGeometry(QtCore.QRect(410, 610, 38, 32))
        self.play_button.setObjectName("play_button")

        self.retranslateUi(remove)
        QtCore.QMetaObject.connectSlotsByName(remove)

    def retranslateUi(self, remove):
        _translate = QtCore.QCoreApplication.translate
        remove.setWindowTitle(_translate("remove", "Form"))
        self.work_button.setText(_translate("remove", "去除水印"))
from qfluentwidgets import CommandBar, Slider, ToolButton, TransparentPushButton
