# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_watermark.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_watermark(object):
    def setupUi(self, watermark):
        watermark.setObjectName("watermark")
        watermark.resize(1160, 810)
        self.commandbar = CommandBar(watermark)
        self.commandbar.setGeometry(QtCore.QRect(0, 0, 541, 34))
        self.commandbar.setObjectName("commandbar")
        self.work_button = TransparentPushButton(watermark)
        self.work_button.setGeometry(QtCore.QRect(490, 610, 176, 30))
        self.work_button.setObjectName("work_button")
        self.detect_button = TransparentPushButton(watermark)
        self.detect_button.setGeometry(QtCore.QRect(680, 610, 176, 30))
        self.detect_button.setObjectName("detect_button")
        self.video = QtWidgets.QGraphicsView(watermark)
        self.video.setGeometry(QtCore.QRect(10, 40, 960, 540))
        self.video.setObjectName("video")
        self.video_slider = Slider(watermark)
        self.video_slider.setGeometry(QtCore.QRect(10, 580, 961, 21))
        self.video_slider.setMaximum(1000)
        self.video_slider.setOrientation(QtCore.Qt.Horizontal)
        self.video_slider.setObjectName("video_slider")
        self.play_button = ToolButton(watermark)
        self.play_button.setGeometry(QtCore.QRect(410, 610, 38, 32))
        self.play_button.setObjectName("play_button")

        self.retranslateUi(watermark)
        QtCore.QMetaObject.connectSlotsByName(watermark)

    def retranslateUi(self, watermark):
        _translate = QtCore.QCoreApplication.translate
        watermark.setWindowTitle(_translate("watermark", "Form"))
        self.work_button.setText(_translate("watermark", "添加水印"))
        self.detect_button.setText(_translate("watermark", "检测水印"))
from qfluentwidgets import CommandBar, Slider, ToolButton, TransparentPushButton
